### ISSUE TITLE
maxBounds

### ISSUE THREAD

**Issue by shiggityshaggs** [Kregap/craftopia-map#28]
It'd be beneficial to set the [maxBounds](https://leafletjs.com/reference.html#map-maxbounds) to prevent users from panning the map out of view.

```
const extent = [
  [-3585, -2559],
  [4607, 4609]
];
```

**Comment by Kregap** [comment]
Good idea, thank you.
Change done in scope of 3dbb596252100b20d320fb32be96dac3fa703f7c. I set more permissive bounds, hope that works for you.
