### ISSUE TITLE
Mouse coordinates fixed-point notation

### ISSUE THREAD

**Issue by shiggityshaggs** [Kregap/craftopia-map#30]
Zooming gives a whole lot of digits:

![image](https://github.com/Kregap/craftopia-map/assets/10870723/c6626731-40e1-4dbc-bc78-b8976ff879de)

It'd look better with a little fix:
```js
map.on('mousemove', (ev) => {
  mouseCoordinates = L.point(ev.latlng.lat.toFixed(1), ev.latlng.lng.toFixed(1))
  coordinatesLabel.updateCoordinates(mouseCoordinates)
})
```
![image](https://github.com/Kregap/craftopia-map/assets/10870723/c55765c6-1371-4d63-9c19-da960358d4eb)

**Comment by Kregap** [comment]
Ah, missed that regression. Thank you.
