### ISSUE TITLE
No markers visible?

### ISSUE THREAD

**Issue by binarycow** [Kregap/craftopia-map#36]
When I view the webpage, I do not see any map markers _at all_.

I then thought that perhaps it only shows you markers you search for.  However, if I search for a marker, no results appear.  I tried many different markers, but the most basic search I tried was `Goblin` - I _know_ it exists (it's in the spreadsheet), I used the right casing, and I used the full word, with no leading or trailing spaces.

Browser: Microsoft Edge; Version 127.0.2651.86 (Official build) (64-bit)
Operating System: Windows 11 Pro 23H2 (OS Build 22631.3880)

Screenshot of what I see:

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/ffff75af-5064-405c-b796-4d216fa2c97a">

**Comment by Kregap** [comment]
Hi, thank you for the report. Is the issues still occurring? I'm unable to reporoduce it using variety of browsers.

**Comment by binarycow** [comment]
I don't know why it wasn't working before, but it is now 🤷‍♂️
